In [1]:
# 3. import numpy as np
import numpy as np

In [2]:
#%matplotlib inline
#import matplotlib.pyplot as plt

In [6]:
#from numpy import *

In [11]:
a = array([0,1,2,3,4,5,6,7,8])

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8
Matrix = array([[0,1,2], [3,4,5], [6,7,8]])

Matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# 5.What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [15]:
# 6. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\DELL PC\Miniconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in sqrt
  from ipykernel import kernelapp as app


False

In [28]:
# 7. Create a random vector of size 30 and find the mean value

x = random.rand(30)
x
meanx = mean(x)
meanx

0.4602886567573285

In [32]:
# 8/9. Multiply 5x3 matrix by a 3 x 2 matrix

v = ones((5,3))
y = ones((3,2))
results = matmul(v,y)
results

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [18]:
# 10. Create a random vector of size 10 and sort it
z =np.random.rand(10)
np.sort(z)

array([ 0.16378246,  0.36413005,  0.4178118 ,  0.49121055,  0.59113771,
        0.60949512,  0.61519397,  0.6272685 ,  0.6893102 ,  0.76278775])

In [20]:
# 11. Create a random of size 100 and replace the maximum value by 0
x =np.random.rand(100)
x[np.where(x == x.max())]=0

In [23]:
# 12. How to get the diagonal of a dot product?
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)
np.diag(np.dot(np.dot(a, b), a.T))

array([  60,  672, 1932, 3840, 6396])